name = "sink2"
main = "backend/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sink_db"
database_id = "3b6b617f-b697-407e-bf55-40bf463019e1"
